### ISSUE TITLE
网络输入问题

### ISSUE THREAD

**Issue by HTT1995** [YangYang/CRNN_mapping_baseline#2]
请问网络的输入是多少帧，对应输出是多少帧，【batch_size，in_c，T,  nfft】是输入的维度，我做过实验，按照论文中的数据，也就是输入是【batch_size,1,500,256】,但是结果并不理想，请问你这个实验是多少帧作为一个batch，我认为500是不是太多了

**Comment by Andong-Li-speech** [comment]
> 请问网络的输入是多少帧，对应输出是多少帧，【batch_size，in_c，T, nfft】是输入的维度，我做过实验，按照论文中的数据，也就是输入是【batch_size,1,500,256】,但是结果并不理想，请问你这个实验是多少帧作为一个batch，我认为500是不是太多了

文章并不需要将语音的帧长固定，采用的是变长输入。在每个mini-batch中以最长帧将其余语音帧数补全，之后再计算loss的时候通过mask将多余长度帧排除计算之外。

**Comment by YangYang** [comment]
是的，对于帧长不固定，在每个batch上将帧长补齐即可。防止计算loss出问题，在补齐之前将每条语音的长度存下来，在计算loss时候，用一个（0，1）mask可以直接将补齐的部分给去掉。

**Comment by YangYang** [comment]
非常抱歉现在才回复，之前可能由于一些事情打扰忘记了
